
export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3000/api";

export const ERROR_CODES = {
  EMAIL_EXISTS: "USR.EMAIL_EXISTS",           
  EMAIL_NOT_FOUND: "USR.EMAIL_NOT_FOUND",     
  INVALID_PASSWORD: "USR.INVALID_PASSWORD",   
  ACCOUNT_DISABLED: "USR.ACCOUNT_DISABLED",   
  TOKEN_EXPIRED: "AUTH.TOKEN_EXPIRED",       
  TOKEN_INVALID: "AUTH.TOKEN_INVALID",        
  VALIDATION_FAILED: "COMMON.VALIDATION_FAILED",
  UNKNOWN_ERROR: "COMMON.UNKNOWN_ERROR",        
  
  
  USER_NOT_FOUND: "USR.NOT_FOUND",
  ACCOUNT_NOT_VERIFIED: "USR.ACCOUNT_NOT_VERIFIED",
  USER_INACTIVE: "USR.USER_INACTIVE",

  CATEGORY_NAME_REQUIRED: "CATEGORY.NAME_REQUIRED",
  CATEGORY_ALREADY_EXISTS: "CATEGORY.ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY.NOT_FOUND", 
};

